#!/bin/bash

set -e

if [ "$1" = "configure" ]; then
	useradd --system --home /srv/vault --shell /usr/sbin/nologin vault 2> /dev/null || true
	mkdir -p /srv/vault 2> /dev/null || true
	chown -R vault: /srv/vault 2>&1 /dev/null || true
fi

#DEBHELPER#

exit 0
