#!/bin/bash

set -e

# Automatically added by dh_installsystemd/13.10.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
        deb-systemd-invoke stop 'vault.service' >/dev/null || true
fi
# End automatically added section
